#!/bin/bash

#    This file is part of gdrive sync.
#
#    gdrive sync is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    gdrive sync is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with gdrive sync. If not, see <http://www.gnu.org/licenses/>.

# Set a variable for where this script lives
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Set a couple of important variables
if [ ! -f "$DIR"/gdrive-vars ]; then
   #DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
   echo ""
   echo "!! - Configuration file not found"
   echo "!! - Please create a gdrive-vars file in $DIR"
   echo ""
   echo "Config file needs content below with your preferred values instead:"
   echo ""
   ## MAKE SURE THESE ARE ALL STILL NEEDED
   echo "MOUNTPOINT=\"/home/edexample/box\""
   echo "LOCALSYNC=\"/home/edexample/stuff\""
   echo "REMOTESYNC=\"/home/edexample/box/stuff\""
   echo "CONFDIR=\"/home/edexample/.lsyncd\""
   echo "LOGFILE=\"$CONFDIR/lsyncd.log\""
   echo ""
   exit 1
else
   source "$DIR"/gdrive-vars
fi

# Run in an infinite loop
while true 
do 
inotifywait -r -e modify,attrib,close_write,move,create,delete "$LOCALSYNC" && unison gdrive 2>/dev/null | grep "<-?->"
done
